[tool.poetry]
name = "drf"
version = "0.1.0"
description = ""
authors = ["vadbarriens <burinvad@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
